"""empty message

Revision ID: 46de6f9372f3
Revises: 75423d3bb549
Create Date: 2017-07-13 03:32:27.857141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46de6f9372f3'
down_revision = '75423d3bb549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('achieved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'achieved')
    # ### end Alembic commands ###
