"""empty message

Revision ID: 490f83750d3a
Revises: 73dddc997c49
Create Date: 2017-06-25 01:23:06.862716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490f83750d3a'
down_revision = '73dddc997c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('lname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
