"""empty message

Revision ID: 4bc7346542f0
Revises: 
Create Date: 2017-07-01 16:06:23.143949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc7346542f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('activityid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('activityid')
    )
    op.create_table('author',
    sa.Column('authorid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('authorid')
    )
    op.create_table('category',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('categoryid')
    )
    op.create_table('milestone',
    sa.Column('milestoneid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('milestoneid')
    )
    op.create_table('phase',
    sa.Column('phaseid', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('phaseid')
    )
    op.create_table('resource',
    sa.Column('resourceid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('resourceid')
    )
    op.create_table('title',
    sa.Column('titleid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('subtitle', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('titleid')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('authentication',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('salt', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['userid'], [u'users.userid'], ),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('belongs_to',
    sa.Column('titleid', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryid'], [u'category.categoryid'], ),
    sa.ForeignKeyConstraint(['titleid'], [u'title.titleid'], ),
    sa.PrimaryKeyConstraint('titleid', 'categoryid')
    )
    op.create_table('by',
    sa.Column('authorid', sa.Integer(), nullable=False),
    sa.Column('titleid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorid'], [u'author.authorid'], ),
    sa.ForeignKeyConstraint(['titleid'], [u'title.titleid'], ),
    sa.PrimaryKeyConstraint('authorid', 'titleid')
    )
    op.create_table('consists_of',
    sa.Column('phaseid', sa.Integer(), nullable=False),
    sa.Column('activityid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activityid'], [u'activity.activityid'], ),
    sa.ForeignKeyConstraint(['phaseid'], [u'phase.phaseid'], ),
    sa.PrimaryKeyConstraint('phaseid', 'activityid')
    )
    op.create_table('event',
    sa.Column('activityid', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['activityid'], [u'activity.activityid'], ),
    sa.PrimaryKeyConstraint('activityid')
    )
    op.create_table('has',
    sa.Column('titleid', sa.Integer(), nullable=False),
    sa.Column('phaseid', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['phaseid'], [u'phase.phaseid'], ),
    sa.ForeignKeyConstraint(['titleid'], [u'title.titleid'], ),
    sa.PrimaryKeyConstraint('titleid', 'phaseid')
    )
    op.create_table('human_resource',
    sa.Column('resourceid', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resourceid'], [u'resource.resourceid'], ),
    sa.PrimaryKeyConstraint('resourceid')
    )
    op.create_table('includes',
    sa.Column('phaseid', sa.Integer(), nullable=False),
    sa.Column('milestoneid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['milestoneid'], [u'milestone.milestoneid'], ),
    sa.ForeignKeyConstraint(['phaseid'], [u'phase.phaseid'], ),
    sa.PrimaryKeyConstraint('milestoneid', 'phaseid')
    )
    op.create_table('material_resource',
    sa.Column('resourceid', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('unitcost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resourceid'], [u'resource.resourceid'], ),
    sa.PrimaryKeyConstraint('resourceid')
    )
    op.create_table('owns',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('phaseid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phaseid'], [u'phase.phaseid'], ),
    sa.ForeignKeyConstraint(['userid'], [u'users.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'phaseid')
    )
    op.create_table('publishing',
    sa.Column('titleid', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('pagecount', sa.Integer(), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['titleid'], [u'title.titleid'], ),
    sa.PrimaryKeyConstraint('titleid'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('sales',
    sa.Column('titleid', sa.Integer(), nullable=False),
    sa.Column('totalsales', sa.Float(), nullable=True),
    sa.Column('internationalsales', sa.Float(), nullable=True),
    sa.Column('localsales', sa.Float(), nullable=True),
    sa.Column('regionalsales', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['titleid'], [u'title.titleid'], ),
    sa.PrimaryKeyConstraint('titleid')
    )
    op.create_table('uses',
    sa.Column('activityid', sa.Integer(), nullable=False),
    sa.Column('resourceid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activityid'], [u'activity.activityid'], ),
    sa.ForeignKeyConstraint(['resourceid'], [u'resource.resourceid'], ),
    sa.PrimaryKeyConstraint('activityid', 'resourceid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uses')
    op.drop_table('sales')
    op.drop_table('publishing')
    op.drop_table('owns')
    op.drop_table('material_resource')
    op.drop_table('includes')
    op.drop_table('human_resource')
    op.drop_table('has')
    op.drop_table('event')
    op.drop_table('consists_of')
    op.drop_table('by')
    op.drop_table('belongs_to')
    op.drop_table('authentication')
    op.drop_table('users')
    op.drop_table('title')
    op.drop_table('resource')
    op.drop_table('phase')
    op.drop_table('milestone')
    op.drop_table('category')
    op.drop_table('author')
    op.drop_table('activity')
    # ### end Alembic commands ###
