"""empty message

Revision ID: 73dddc997c49
Revises: 
Create Date: 2017-06-25 00:49:10.387919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dddc997c49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('author', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.drop_column('author', 'name')
    op.add_column('title', sa.Column('status', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('fname', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('lname', sa.String(length=80), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    op.drop_column('user', 'email')
    op.drop_column('title', 'status')
    op.add_column('author', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('author', 'lastname')
    op.drop_column('author', 'firstname')
    # ### end Alembic commands ###
