"""empty message

Revision ID: 75423d3bb549
Revises: bfb0c9efe9e6
Create Date: 2017-07-10 00:46:50.877171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75423d3bb549'
down_revision = 'bfb0c9efe9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase', 'current')
    # ### end Alembic commands ###
