"""empty message

Revision ID: bfb0c9efe9e6
Revises: 4bc7346542f0
Create Date: 2017-07-07 04:48:37.080452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb0c9efe9e6'
down_revision = '4bc7346542f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('has', 'stage')
    op.add_column('phase', sa.Column('stage', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase', 'stage')
    op.add_column('has', sa.Column('stage', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('activity', 'completed')
    # ### end Alembic commands ###
